service: EV-Map-Lambdas

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: eu-west-2
  environment:
    MAPBOX_API_TOKEN: ${env:MAPBOX_API_TOKEN}

functions:
  hello:
    handler: ./lambdas/handler.hello
    events:
      - http:
          path: /hello
          method: get
  directions:
    handler: ./lambdas/directions.directions
    events:
      - http:
          path: /directions
          method: get
